CREATE DATABASE Pizzeria;

USE Pizzeria;

CREATE TABLE CLIENTES(
    ID_CLIENTES INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    APELLIDO VARCHAR(100),
    SEGUNDO_APELLIDO  VARCHAR(100),
    DIRECCION VARCHAR(300),
    CLAVE VARCHAR(255),
    TELEFONO INT
);

Create Table TIPO_CARNES(
    ID_TIPOCARNE INT PRIMARY KEY, 
    TIPO_CARNE VARCHAR(100) NOT NULL,
    PRECIO DECIMAL(20,2)
);

-- Insertar datos a tablas de carnes
INSERT INTO TIPO_CARNES VALUES (1, 'Pepperoni', 300.00);
INSERT INTO TIPO_CARNES VALUES (2, 'Jamón', 524.23);
INSERT INTO TIPO_CARNES VALUES (3, 'Carne de res', 850.00);
INSERT INTO TIPO_CARNES VALUES (4, 'Tocineta', 910.12);
INSERT INTO TIPO_CARNES VALUES (5, 'Carne italiana', 1200.00);

CREATE TABLE TIPOS_VEGETALES (
    ID_TIPOVEGETALES INT PRIMARY KEY,
    TIPO_VEGETALES VARCHAR (100) NOT NULL,
    PRECIO DECIMAL(20,2)
);

-- Insertar datos a tablas de vegetales
INSERT INTO TIPOS_VEGETALES VALUES (1, 'Chile dulce', 50.00);
INSERT INTO TIPOS_VEGETALES VALUES (2, 'Cebolla', 50.00);
INSERT INTO TIPOS_VEGETALES VALUES (3, 'Tomate', 40.00);
INSERT INTO TIPOS_VEGETALES VALUES (4, 'Aceituna negra', 80.00);
INSERT INTO TIPOS_VEGETALES VALUES (5, 'Chile jalapeño', 30.00);

CREATE TABLE TIPO_MASAS (
    ID_TIPO_MASA INT PRIMARY KEY,
    TIPO_MASA VARCHAR(100) NOT NULL,
    PRECIO DECIMAL(20,2)
);

-- Insertar datos a tablas de masa
INSERT INTO TIPO_MASAS VALUES (1, 'Pasta delgada', 1000.00);
INSERT INTO TIPO_MASAS VALUES (2, 'Pasta gruesa',1100.00);
INSERT INTO TIPO_MASAS VALUES (3, 'Clásica',1200.00);
INSERT INTO TIPO_MASAS VALUES (4, 'Borde de queso',1500.00);

CREATE TABLE TAMANHO_PIZZA(
    ID_TAMANHO INT PRIMARY KEY,
    TAMANHO VARCHAR(50) NOT NULL,
    PRECIO DECIMAL(20,2)
);

-- Insertar datos a tablas de tamaño de pizza
INSERT INTO TAMANHO_PIZZA VALUES (1, 'Personal - 4 pedazos', 1500.00);
INSERT INTO TAMANHO_PIZZA VALUES (2, 'Pequeña - 8 pedazos', 2000.00);
INSERT INTO TAMANHO_PIZZA VALUES (3, 'Mediana - 12 pedazos', 2500.00);
INSERT INTO TAMANHO_PIZZA VALUES (4, 'Grande - 16 pedazos', 3000.00);
INSERT INTO TAMANHO_PIZZA VALUES (5, 'Familiar - 20 pedazos', 6000.00);

CREATE TABLE PIZZA(
    ID_PIZZA INT AUTO_INCREMENT PRIMARY KEY,
    ID_TIPOCARNE INT,
    ID_TIPOVEGETALES INT,
    ID_TIPO_MASA INT,
    ID_TAMANHO INT,
    PRECIO_FINAL DECIMAL(20,2),
    FECHA DATETIME,
    DESCRIPCION VARCHAR(500),
    ID_CLIENTES INT,
    FOREIGN KEY (ID_TAMANHO) REFERENCES TAMANHO_PIZZA(ID_TAMANHO),
    FOREIGN KEY (ID_TIPOCARNE) REFERENCES TIPO_CARNES(ID_TIPOCARNE),
    FOREIGN KEY (ID_TIPOVEGETALES) REFERENCES TIPOS_VEGETALES(ID_TIPOVEGETALES),
    FOREIGN KEY (ID_TIPO_MASA) REFERENCES TIPO_MASAS(ID_TIPO_MASA),
    FOREIGN KEY (ID_CLIENTES) REFERENCES CLIENTES(ID_CLIENTES)
);

/*CREATE TABLE COMPRAS (
    ID_COMPRA INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT,
    ID_PIZZA INT,
    DESCRIPCION VARCHAR(200),
    FECHA DATETIME,
    TOTAL DECIMAL(20,2),
    FOREIGN KEY(ID_PIZZA) REFERENCES PIZZA(ID_PIZZA),
    FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTES)
);*/
